### ISSUE TITLE
problems with using large datasets in mmdb

### ISSUE THREAD

**Issue by jack-reso** [fo0/geolocation-service#3]
when i write data(e.g.:enc) into mmdb file,i goes wrong.    enc is too large,almost 2GB,how can i insert into mmdb?

**Comment by fo0** [comment]
Hi @jack-reso I am not an expert of mmdb. All I can do is to give you the right steps how to maybe solve your problem:
Checking our the docs of mmdb:
- https://github.com/maxmind/MaxMind-DB/blob/main/MaxMind-DB-spec.md
- https://dev.maxmind.com/geoip/importing-databases/mysql?lang=en

Contact MMDB https://maxmind.github.io/MaxMind-DB/

I just used this database to feed my spring service. 

Good look
